### ISSUE TITLE
question about deployment to heroku

### ISSUE THREAD

**Issue by mjcc30** [montrealelixir/website#110]
Hello everybody !

I'm trying to deploy a phoenix app on Kubernetes with waypoint and I see that we can use a Heroku custom buildpack to do this :
https://github.com/hashicorp/waypoint-examples/issues/34
https://www.waypointproject.io/plugins/pack

I understand a little how to use waypoint but I don't know how I can use Heroku build pack with it, nor how Heroku build pack works.

Do you have some information about how to deploy the phoenix app with Heroku buildpack?

Thank you very much!

**Comment by nicholasjhenry** [comment]
I would recommend checking out the Phoenix guides:

https://hexdocs.pm/phoenix/heroku.html
