### ISSUE TITLE
Display 3 most recent tweets 

### ISSUE THREAD

**Issue by nicholasjhenry** [montrealelixir/website#13]
![image](https://user-images.githubusercontent.com/40253/27605291-3ccc64d6-5b4a-11e7-8eec-d9893ef108b3.png)

**Comment by kpolitowicz** [comment]
Now, getting the last 3 tweets via Twitter API can be tough, starting with getting API token (I'm not aware of any unauthenticated call to get the data) and finishing with rolling out websockets to make sure new tweets show up w/o reloading the page. 

While ultimately this will give more control over the display styling (and less "big brothery" tracking), how do you feel about using the embedded timeline (https://publish.twitter.com/?url=https%3A%2F%2Ftwitter.com%2FTwitterDev&ref_src=twsrc%5Etfw&ref_url=https%3A%2F%2Fdev.twitter.com%2Fweb%2Fembedded-timelines%2Fuser#) for now? Something around 500x300px looks pretty well (see screenshot).
![screen shot 2017-10-08 at 3 16 14 am](https://user-images.githubusercontent.com/190437/31314775-2d917870-abd7-11e7-88d8-92d902b49182.png)

**Comment by frahugo** [comment]
Hi @kpolitowicz.  I have developed an interface to Twitter that I will present at the next meet-up, unless some other presenters volunteer for this week.  It's all homemade using OTP and the Twitter API.  Thanks for looking at this!

**Comment by kpolitowicz** [comment]
Cool @frahugo - I guess I'll wait for your Twitter interface and see how to integrate my PR #18 :)
