### ISSUE TITLE
Meetup and Twitter links should open in new window/tab

### ISSUE THREAD

**Issue by kpolitowicz** [montrealelixir/website#25]
See screenshot.

I think it would be a better UX to open the external websites in new window. Note that links in tweets within the twitter feed already open like that.

![montreal_elixir_links](https://user-images.githubusercontent.com/190437/31590945-8bc81f5a-b1e7-11e7-93dc-72b8a06f8382.png)

**Comment by secondspass** [comment]
I can give this a go, once my other PR (#26) is approved or rejected 😁.

**Comment by secondspass** [comment]
![selection_004](https://user-images.githubusercontent.com/17310566/31753073-fe4cc05a-b4ab-11e7-9226-0ce296ca8b52.png)
What about these links though? Should they all open in new tabs?

**Comment by nicholasjhenry** [comment]
I guess for consistency sakes that makes sense to do those as well, thanks @dragsubil
