### ISSUE TITLE
Clean-up the configuration files

### ISSUE THREAD

**Issue by frahugo** [montrealelixir/website#42]
The database configuration for dev and test should be in a `secret` file, as the developer might have a different usename/password.  They are now hardcoded in `dev.exs` and `test.exs`.

**Comment by gcauchon** [comment]
I think we should follow the [Twelve-Factor](https://12factor.net/config) methodology for configuration and use `ENV`, not secret files, even for development.

I personally use [`direnv`](https://direnv.net/) with a `.envrc` file that is ignored in both my global and project specific `.gitignore`.  There are many alternatives, one is [`nv`](https://github.com/jcouture/nv) a tool made by a teammate from Mirego.

**Comment by nicholasjhenry** [comment]
@gcauchon good call. 👍  We can create a `.env-sample` file with the necessary vars and then that can be copied and renamed to be used for whatever tool the developer uses. We can suggest a tool in the README to help new-comers get started quickly.

**Comment by gcauchon** [comment]
Yes! I'll change the setup and update the README to reflect the development setup changes.

I'll also include a `docker-compose.yml` file to run a Postgres instance using docker. There nothin in the DB yet, but it still is a mandatory softeare dependency based on the config files.
