### ISSUE TITLE
Switch to Docker for TravisCI

### ISSUE THREAD

**Issue by nicholasjhenry** [montrealelixir/website#44]
https://docs.travis-ci.com/user/docker/

This could eventually be used for development as well.

**Comment by gcauchon** [comment]
Are we also thinking about replacing the `mix`-based buildpack with docker deployment that is available on Heroku?

https://devcenter.heroku.com/articles/container-registry-and-runtime

This will be get even simpler when the `distillery` features will be merge directly in `mix`, but for now, it still is super simple to build an OTP release binary and warp it in a lightweight Docker container.

**Comment by nicholasjhenry** [comment]
@gcauchon yes, that was the intention :-) The thinking was introducing Docker into the project via the build on TravisCI and then start looking at deployment. Certainly no need to follow that path though if you're interested in contributing to the deployment.

**Comment by gcauchon** [comment]
I'll change the Travis setup first and we'll go from there...

**Comment by nicholasjhenry** [comment]
Resolved in #91
