### ISSUE TITLE
Merge codebase to a single Phoenix monolith

### ISSUE THREAD

**Issue by gcauchon** [montrealelixir/website#48]
This is more an _open discussion_ than an _issue_, but I was not shure where would be the right place to have this conversation. If it is not, let me know where would be the appropriate channel to talk about this.

I don't understand the need to bundle the website as many umbrella apps when a single monolith leveraging Phoenix's [Context](https://hexdocs.pm/phoenix/contexts.html) would be enough for the separation of concerns.

Furthermore, the codebase would be fare more simpler to understand for a beginner that is starting in `Elixir`.

**Comment by nicholasjhenry** [comment]
> This is more an open discussion than an issue, but I was not shure where would be the right place to have this conversation. If it is not, let me know where would be the appropriate channel to talk about this.

@gcauchon totally fine to open up a discussion here. I won't reply right now, but I do have a few thoughts on this. Stay tuned ;-)

**Comment by nicholasjhenry** [comment]
As discussed with @frahugo at a previous meetup, we decided to go with an umbrella to demonstrate how we can create decouple applications with focused concerns. This is one of the highlights for building Elixir applications.

I'm going to close this issue, but free to open if you wish to discuss further.
