### ISSUE TITLE
Twitter updates are gone

### ISSUE THREAD

**Issue by saulecabrera** [montrealelixir/website#53]
Just noted that the twitter updates section is not loading any tweets. 
Not sure if it has something to do with the recent changes.

<img width="355" alt="screen shot 2018-04-22 at 6 11 12 pm" src="https://user-images.githubusercontent.com/1423601/39100478-2e7ed4a4-4659-11e8-99ed-5664b732e5e0.png">

**Comment by saulecabrera** [comment]
Locally everything seems to be working fine.

**Comment by nicholasjhenry** [comment]
Seems to be working now. Let's re-open if we see this occur again.

<img width="368" alt="screen shot 2018-05-05 at 4 48 21 pm" src="https://user-images.githubusercontent.com/40253/39667439-4083b82e-5084-11e8-9867-7a9c993502a8.png">
